### ISSUE TITLE
Allow inline json instead of file

### ISSUE THREAD

**Issue by justgook** [posthtml/posthtml-head-elements#6]
I would like to use configure head as inline json, form same config instead of using external file

**Comment by Scrum** [comment]
@justgook Hi, yes you can for example
```js
require('posthtml-head-elements')({headElements: {/* you inline json */}})
```

or are you talking about something else?

**Comment by justgook** [comment]
im about using it over CLI / config json..
https://github.com/posthtml/posthtml-head-elements/blob/master/index.js#L127  - based on that line - it will try to load file..

**Comment by justgook** [comment]
if i run via posthtml-cli - that config will fail..

```
module.exports = {
    posthtml: {
        plugins: {
            'posthtml-head-elements': {
                headElements:
                    {
                        "meta": [
                            {
                                "charset": "utf-8"
                            },
                        ]
                    }
            }
        }
    }
}```

**Comment by Scrum** [comment]
@justgook can you create a repository with an example of playing back an error?

**Comment by justgook** [comment]
in progress.. now ill create that PR - and later evening will push updates to repo.

**Comment by Scrum** [comment]
> now ill create that PR - and later evening will push updates to repo.
Thank you very cool 👍
